// Generated by CoffeeScript 1.4.0
(function() {
  var $, ls, setNotification;

  $ = jQuery;

  ls = localStorage;

  setNotification = function() {
    var creator, description, image, link, maxlength, title;
    title = ls.notificationTitle;
    link = ls.notificationLink;
    description = ls.notificationDescription;
    creator = ls.notificationCreator;
    image = ls.notificationImage;
    maxlength = 90;
    if (maxlength < description.length) {
      description = description.substring(0, maxlength) + '...';
    }
    $('#notification').click(function() {
      Browser.openTab(link);
      return window.close;
    });
    $('#notification').html('\
    <div class="item">\
      <div class="title">' + title + '</div>\
      <img src="' + image + '" />\
      <div class="textwrapper">\
        <div class="emphasized">- Av ' + creator + '</div>\
        <div class="description">' + description + '</div>\
      </div>\
    </div>\
    </a>');
    if (ls.notificationFeedName === 'online') {
      return News.online_getImage(link, function(link, image) {
        return $('img').prop('src', image);
      });
    }
  };

  $(function() {
    return setNotification();
  });

}).call(this);
