// Generated by CoffeeScript 1.4.0
(function() {
  var $, ls, setNotification;

  $ = jQuery;

  ls = localStorage;

  setNotification = function() {
    var creator, description, link, maxlength, title;
    title = ls.notificationTitle;
    link = ls.notificationLink;
    description = ls.notificationDescription;
    creator = ls.notificationCreator;
    maxlength = 90;
    if (maxlength < description.length) {
      description = description.substring(0, maxlength) + '...';
    }
    $('#notification').click(function() {
      Browser.openTab(link);
      return window.close;
    });
    return News.online_getImage(link, function(id, image) {
      return $('#notification').html('\
      <div class="item">\
        <div class="title">' + title + '</div>\
        <img id="' + id + '" src="' + image + '" />\
        <div class="textwrapper">\
          <div class="emphasized">- Av ' + creator + '</div>\
          <div class="description">' + description + '</div>\
        </div>\
      </div>\
      </a>');
    });
  };

  $(function() {
    setNotification();
    return setTimeout((function() {
      return window.close();
    }), 5000);
  });

}).call(this);
