// Generated by CoffeeScript 1.4.0
(function() {
  var $, setSubscription;

  $ = jQuery;

  setSubscription = function() {
    var image, images, random, width;
    images = numbers.slice(1, 28);
    random = Math.floor(Math.random() * images.length);
    image = './meme/' + images[random] + '.jpg';
    $('#subscription').click(function() {
      Browser.openTab('options.html');
      return window.close;
    });
    width = $('#subscription').width();
    return $('#subscription').html('<img src="' + image + '" width="' + width + '" />');
  };

  $(function() {
    $.ajaxSetup(AJAX_SETUP);
    setSubscription();
    return setTimeout((function() {
      return window.close();
    }), 6000);
  });

}).call(this);
