// Generated by CoffeeScript 1.3.3
(function() {
  var connectGoogleAnalytics, iterationCounter, mainLoop;

  if (DEBUG) {
    localStorage.clear();
  }

  if (localStorage.everConnected === void 0) {
    if (localStorage.showOfficeStatus === void 0) {
      localStorage.showOfficeStatus = 'true';
    }
    if (localStorage.showNotifications === void 0) {
      localStorage.showNotifications = 'true';
    }
    if (localStorage.showCantinaMenu === void 0) {
      localStorage.showCantinaMenu = 'true';
    }
    if (localStorage.openChatter === void 0) {
      localStorage.openChatter = 'false';
    }
    if (!DEBUG) {
      chrome.tabs.create({
        url: chrome.extension.getURL("options.html"),
        selected: true
      });
    }
  }

  if (localStorage.openChatter === 'true') {
    chrome.tabs.create({
      url: CHATTER_URL,
      selected: false
    });
  }

  cantinaMenu_reset();

  officeStatus_reset();

  localStorage.everConnected = 'false';

  localStorage.wasConnected = 'true';

  localStorage.mainLoopTimeout = MAIN_LOOP_QUICK_TIMEOUT;

  iterationCounter = 1;

  $.ajaxSetup({
    timeout: AJAX_REQUEST_TIMEOUT
  });

  mainLoop = function() {
    var loopTimeout;
    if (DEBUG) {
      console.log('\n# ' + iterationCounter);
    }
    if (navigator.onLine) {
      if (localStorage.wasConnected === 'false' || localStorage.everConnected === 'false') {
        officeStatus_update();
        fetchFeed(unreadCount);
        cantinaMenu_update();
      }
      if (localStorage.everConnected === 'false') {
        connectGoogleAnalytics();
      } else {
        if (iterationCounter % REFRESH_OFFICE_STATUS_INTERVAL === 0) {
          officeStatus_update();
        }
        if (iterationCounter % REFRESH_NEWS_FEED_INTERVAL === 0) {
          fetchFeed(unreadCount);
        }
        if (iterationCounter % REFRESH_CANTINA_MENU_INTERVAL === 0) {
          cantinaMenu_update();
        }
      }
      localStorage.everConnected = 'true';
      localStorage.wasConnected = 'true';
    } else {
      officeStatus_disconnected(localStorage.wasConnected);
      localStorage.wasConnected = 'false';
    }
    iterationCounter++;
    if (10000 < iterationCounter) {
      iterationCounter = 1;
    }
    loopTimeout = Number(localStorage.mainLoopTimeout);
    if (DEBUG || localStorage.wasConnected === 'false') {
      loopTimeout = MAIN_LOOP_QUICK_TIMEOUT;
    }
    return setTimeout((function() {
      return mainLoop();
    }), loopTimeout);
  };

  connectGoogleAnalytics = function() {
    var script;
    if (DEBUG) {
      console.log('connecting google analytics');
    }
    script = document.createElement("script");
    script.type = 'text/javascript';
    script.src = 'js/google_analytics.js';
    return document.getElementsByTagName("head")[0].appendChild(script);
  };

  $(function() {
    return mainLoop();
  });

}).call(this);
