// Generated by CoffeeScript 1.3.3
(function() {
  var $, setNotification;

  $ = jQuery;

  setNotification = function() {
    var creator, date, desc, diff, id, link, maxlength, title, total;
    id = localStorage.notificationId;
    link = localStorage.notificationLink;
    creator = localStorage.notificationCreator;
    date = localStorage.notificationDate;
    title = localStorage.notificationTitle;
    desc = localStorage.notificationDescription;
    maxlength = 90;
    total = title.length + desc.length;
    if (maxlength < total) {
      diff = total - maxlength;
      desc = desc.substring(0, desc.length - diff) + '...';
    }
    return getImageUrlForId(id, function(id, image) {
      return $('#notification').html('\
      <a href="' + link + '">\
      <div class="item" onclick="openUrl(\'' + link + '\'); window.close();">\
        <header>\
          <span class="creator">' + creator + '</span>\
          <span class="date"> <b>::</b> ' + date + '</span>\
        </header>\
        <img id="' + id + '" src="' + image + '" />\
        <div class="textwrapper">\
          <span class="title">' + title + ' :: </span>\
          <span class="description">' + desc + '</span>\
        </div>\
      </div>\
      </a>');
    });
  };

  $(function() {
    setNotification();
    return setTimeout((function() {
      return window.close();
    }), DESKTOP_NOTIFICATION_TIMEOUT);
  });

}).call(this);
