// Generated by CoffeeScript 1.3.3
(function() {
  var $, displayOnPageNotification, fadeInCanvas, pageFlipCursorBlinking, resizeBackgroundImage, testDesktopNotification;

  $ = jQuery;

  resizeBackgroundImage = function() {
    if (1550 < $(window).width()) {
      return $('#background').attr("style", "background:url('img/background-large.png') center center no-repeat;");
    } else if (1200 < $(window).height()) {
      return $('#background').attr("style", "background:url('img/background-large-vertical.png') center center no-repeat;");
    } else {
      return $('#background').attr("style", "background:url('img/background-medium.png') center center no-repeat;");
    }
  };

  displayOnPageNotification = function() {
    $("#notification").fadeIn(200);
    return setTimeout((function() {
      return $("#notification").fadeOut(200);
    }), OPTIONS_NOTIFICATION_TIMEOUT);
  };

  pageFlipCursorBlinking = function() {
    return $(".pageflipcursor").animate({
      opacity: 0
    }, "fast", "swing", function() {
      return $(this).animate({
        opacity: 1
      }, "fast", "swing");
    });
  };

  testDesktopNotification = function() {
    var notification;
    notification = webkitNotifications.createHTMLNotification('notification.html');
    return notification.show();
  };

  fadeInCanvas = function() {
    webGLStart();
    return $('#LessonCanvas').animate({
      opacity: 1
    }, 1300, 'swing', function() {
      return setTimeout((function() {
        return $('#LessonCanvas').animate({
          opacity: 0
        }, 1300, 'swing');
      }), 200);
    });
  };

  $(function() {
    $('#background').attr("style", "background:url('img/background-medium.png') center center no-repeat;");
    $('#pageflipbg').attr("style", "background:transparent url('img/options-pageflipbg.png') no-repeat left bottom;");
    $('#pageflip').attr("style", "background:transparent url('img/options-pageflip.png') no-repeat left bottom;");
    $('input:checkbox').each(function(index, element) {
      return element.checked = localStorage[element.id] === "true";
    });
    $(window).bind("resize", resizeBackgroundImage);
    resizeBackgroundImage();
    if (OPERATING_SYSTEM === 'Windows') {
      $('#pagefliptext').attr("style", "bottom:9px;");
      $('#pagefliplink').attr("style", "bottom:9px;");
    }
    setInterval((function() {
      return pageFlipCursorBlinking();
    }), 600);
    setTimeout((function() {
      return $('#plusonebutton').fadeIn(150);
    }), 1100);
    $('#notification').click(function() {
      return fadeInCanvas();
    });
    return $('input:checkbox').click(function() {
      localStorage[this.id] = this.checked;
      if (this.id === 'showOfficeStatus' && this.checked === false) {
        officeStatus_disable();
      } else if (this.id === 'showOfficeStatus' && this.checked === true) {
        officeStatus_update();
      }
      if (this.id === 'showNotifications' && this.checked === true) {
        testDesktopNotification();
      }
      if (this.id === 'showCantinaMenu' && this.checked === false) {
        cantinaMenu_disable();
      } else if (this.id === 'showCantinaMenu' && this.checked === true) {
        cantinaMenu_update();
      }
      return displayOnPageNotification();
    });
  });

}).call(this);
