// Generated by CoffeeScript 1.3.3
(function() {
  var $, iteration, ls, mainLoop, updateNews, updateOffice;

  $ = jQuery;

  ls = localStorage;

  iteration = 0;

  mainLoop = function() {
    var loopTimeout;
    if (DEBUG) {
      console.log("\n#" + iteration);
    }
    if (iteration % UPDATE_OFFICE_INTERVAL === 0 || !navigator.onLine) {
      updateOffice();
    }
    if (iteration % UPDATE_NEWS_INTERVAL === 0 && navigator.onLine) {
      updateNews();
    }
    if (10000 < iteration) {
      iteration = 0;
    } else {
      iteration++;
    }
    if (DEBUG || !navigator.onLine) {
      loopTimeout = BACKGROUND_LOOP_QUICK;
    } else {
      loopTimeout = BACKGROUND_LOOP;
    }
    return setTimeout((function() {
      return mainLoop();
    }), loopTimeout);
  };

  updateOffice = function() {
    if (DEBUG) {
      console.log('updateOffice');
    }
    return Office.get(function(status, title) {
      if (ls.currentStatus !== status || ls.currentStatusTitle !== title) {
        chrome.browserAction.setIcon({
          path: 'img/icon-' + status + '.png'
        });
        chrome.browserAction.setTitle({
          title: title
        });
        ls.currentStatus = status;
        return ls.currentStatusTitle = title;
      }
    });
  };

  updateNews = function() {
    if (DEBUG) {
      console.log('updateNews');
    }
    return fetchFeed(function() {
      var response;
      response = ls.lastResponseData;
      if (response !== null) {
        return unreadCount(response);
      } else {
        return console.log('ERROR: response was null');
      }
    });
  };

  $(function() {
    $.ajaxSetup({
      timeout: 15000
    });
    if (DEBUG) {
      ls.clear();
    }
    ls.removeItem('currentStatus');
    ls.removeItem('currentStatusTitle');
    if (ls.everConnected === void 0) {
      if (ls.showOffice === void 0) {
        ls.showOffice = 'true';
      }
      if (ls.showNotifications === void 0) {
        ls.showNotifications = 'true';
      }
      if (ls.showBus === void 0) {
        ls.showBus = 'true';
      }
      if (ls.showCantina === void 0) {
        ls.showCantina = 'true';
      }
      if (ls.openChatter === void 0) {
        ls.openChatter = 'false';
      }
      if (!DEBUG) {
        chrome.tabs.create({
          url: chrome.extension.getURL("options.html"),
          selected: true
        });
      }
    }
    if (ls.openChatter === 'true') {
      chrome.tabs.create({
        url: 'http://webchat.freenode.net/?channels=online',
        selected: false
      });
    }
    ls.everConnected = ls.wasConnected = 'false';
    setInterval((function() {
      return document.location.reload();
    }), 86400000);
    return mainLoop();
  });

}).call(this);
