// Generated by CoffeeScript 1.3.3
(function() {
  var $, bindBusFields, bindBusSelectors, displayOnPageNotification, fadeInCanvas, ls, pageFlipCursorBlinking, resizeBackgroundImage, testDesktopNotification;

  $ = jQuery;

  ls = localStorage;

  resizeBackgroundImage = function() {
    if (1550 < $(window).width()) {
      return $('#background').attr("style", "background:url('img/background-large.png') center center no-repeat;");
    } else if (1200 < $(window).height()) {
      return $('#background').attr("style", "background:url('img/background-large-vertical.png') center center no-repeat;");
    } else {
      return $('#background').attr("style", "background:url('img/background-medium.png') center center no-repeat;");
    }
  };

  displayOnPageNotification = function() {
    $("#notification").fadeIn(200);
    return setTimeout((function() {
      return $("#notification").fadeOut(200);
    }), 800);
  };

  pageFlipCursorBlinking = function() {
    return $(".pageflipcursor").animate({
      opacity: 0
    }, "fast", "swing", function() {
      return $(this).animate({
        opacity: 1
      }, "fast", "swing");
    });
  };

  testDesktopNotification = function() {
    var notification;
    notification = webkitNotifications.createHTMLNotification('notification.html');
    return notification.show();
  };

  bindBusFields = function(cssSelectors) {
    return $(cssSelectors).keyup(function() {
      var busStop, i, nameStart, requestedDirection, stopId, stopNumbers, suggestions;
      nameStart = $(cssSelectors).val();
      if (nameStart.length > 0) {
        suggestions = Bus.getPotentialStops(nameStart);
        $('#bus_suggestions').html('');
        for (i in suggestions) {
          $('#bus_suggestions').append(suggestions[i] + '<br />');
        }
        if (suggestions.length === 1) {
          busStop = suggestions[0];
          $(cssSelectors).val(busStop);
          $(cssSelectors).blur();
          $('#bus_suggestions').html('');
          stopNumbers = Bus.getStopNumbers(suggestions[0]);
          console.log('stopnumbers: ', stopNumbers);
          requestedDirection = $(cssSelectors).siblings(cssSelectors + '_direction').val();
          console.log('direction: ', requestedDirection);
          if (requestedDirection === 'til byen') {
            for (i in stopNumbers) {
              console.log('checking stopnumbers for 0: ', i);
              if (stopNumbers[i].charAt(5 === 0)) {
                stopId = stopNumbers[i];
              }
            }
          } else if (requestedDirection === 'fra byen') {
            for (i in stopNumbers) {
              console.log('checking stopnumbers for 1: ', i);
              if (stopNumbers[i].charAt(5 === 1)) {
                stopId = stopNumbers[i];
              }
            }
          } else {
            if (DEBUG) {
              console.log('ERROR: No direction found');
            }
          }
          ls.cssSelectors = stopId;
          console.log('http://api.visuweb.no/bybussen/1.0/Departure/Realtime/' + stopId + '/f6975f3c1a3d838dc69724b9445b3466');
          return displayOnPageNotification();
        }
      }
    });
  };

  bindBusSelectors = function(cssSelectors) {
    return $(cssSelectors).change(function() {
      return alert($(cssSelectors).val());
    });
  };

  fadeInCanvas = function() {
    webGLStart();
    return $('#LessonCanvas').animate({
      opacity: 1
    }, 1300, 'swing', function() {
      return setTimeout((function() {
        return $('#LessonCanvas').animate({
          opacity: 0
        }, 1300, 'swing');
      }), 200);
    });
  };

  $(function() {
    if (DEBUG) {
      less.watch();
    }
    $('input:checkbox').each(function(index, element) {
      return element.checked = ls[element.id] === "true";
    });
    $(window).bind("resize", resizeBackgroundImage);
    resizeBackgroundImage();
    if (OPERATING_SYSTEM === 'Windows') {
      $('#pagefliptext').attr("style", "bottom:9px;");
      $('#pagefliplink').attr("style", "bottom:9px;");
    }
    setInterval((function() {
      return pageFlipCursorBlinking();
    }), 600);
    setTimeout((function() {
      return $('#plusonebutton').fadeIn(150);
    }), 1100);
    $('#notification').click(function() {
      return fadeInCanvas();
    });
    bindBusFields('#bus_first');
    bindBusFields('#bus_second');
    bindBusSelectors('#bus_first_direction');
    bindBusSelectors('#bus_second_direction');
    return $('input:checkbox').click(function() {
      ls[this.id] = this.checked;
      if (this.id === 'showOffice' && this.checked === false) {
        chrome.browserAction.setIcon({
          path: 'img/icon-default.png'
        });
        chrome.browserAction.setTitle({
          title: EXTENSION_NAME
        });
      } else if (this.id === 'showOffice' && this.checked === true) {
        Office.get(function(status, title) {
          chrome.browserAction.setIcon({
            path: 'img/icon-' + status + '.png'
          });
          chrome.browserAction.setTitle({
            title: title
          });
          ls.currentStatus = status;
          return ls.currentStatusTitle = title;
        });
      }
      if (this.id === 'showNotifications' && this.checked === true) {
        testDesktopNotification();
      }
      if (this.id === 'useInfoscreen' && this.checked === true) {
        chrome.tabs.create({
          url: chrome.extension.getURL("infoscreen.html"),
          selected: false
        });
      }
      return displayOnPageNotification();
    });
  });

}).call(this);
