// Generated by CoffeeScript 1.4.0
(function() {
  var $, setSubscription;

  $ = jQuery;

  setSubscription = function() {
    $('#subscription').click(function() {
      chrome.tabs.create({
        url: 'https://',
        selected: true
      });
      return window.close;
    });
    return $('#subscription').html('test');
  };

  $(function() {
    setSubscription();
    return setTimeout((function() {
      return window.close();
    }), 5000);
  });

}).call(this);
